name: Build Android
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Android SDK/NDK
        uses: android-actions/setup-android@v3
      - name: Build FFmpegKit
        run: |
          ./android.sh --enable-android-media-codec --enable-srt \
            --disable-arm-v7a --disable-arm-v7a-neon \
            --disable-x86 --disable-x86-64
      - uses: actions/upload-artifact@v4
        with:
          name: ffmpegkit-android
          path: prebuilt/bundle-android-aar/
