name: Build FFmpegKit Android

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
      
      - name: Prerequisites
        run: ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --uninstall "cmake;3.10.2.4988404" "cmake;3.18.1" || true
      
      - name: Set up Android NDK
        run: |
          curl -s "https://dl.google.com/android/repository/android-ndk-r26d-linux.zip" -o ndk.zip
          unzip -q -o ndk.zip -d .ndk
          echo "ANDROID_NDK_ROOT=$PWD/.ndk/$(ls .ndk)" >> $GITHUB_ENV
      
      - name: Build FFmpegKit
        run: |
          ./android.sh \
            --enable-android-media-codec \
            --enable-srt \
            --speed \
            --disable-arm-v7a \
            --disable-arm-v7a-neon \
            --disable-x86 \
            --disable-x86-64
      
      - name: Print build logs
        if: always()
        run: cat build.log
      
      - name: Upload AAR
        uses: actions/upload-artifact@v4
        with:
          name: ffmpegkit-android-arm64
          path: prebuilt/bundle-android-aar/
          retention-days: 30
